name: devmarkaz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.3

  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.0

  path_provider: ^2.0.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  provider: ^6.0.5
  file_picker: ^5.2.5
  permission_handler: ^10.2.0
  # intl: ^0.18.0
  fluttertoast: ^8.2.1
  intl_phone_field: ^3.1.0
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  dropdown_search: ^5.0.5
  carousel_slider: ^4.2.1

  video_player: ^2.6.1
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.11

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#C01719"
  image_path: "assets/logo/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color_dark: "#000000"
  image_dark: assets/logo/logo-white.png
  color: "#ffffff"
  image: assets/logo/logo-black.png


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/logo/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
