// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8YhkfXzmYrC_gCRMruV4-N3Ogf_XwEt0',
    appId: '1:932325401767:web:2cb7c3cb1b2b2fb685a782',
    messagingSenderId: '932325401767',
    projectId: 'dm-managment',
    authDomain: 'dm-managment.firebaseapp.com',
    storageBucket: 'dm-managment.appspot.com',
    measurementId: 'G-2952RZ3R4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi51RurcceCVS6Z6zWkNZwXmmjPBDr8FM',
    appId: '1:932325401767:android:8322bd29fea883ec85a782',
    messagingSenderId: '932325401767',
    projectId: 'dm-managment',
    storageBucket: 'dm-managment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6rqJfnhejTI80zYUROAW1_Wve8wvKlmw',
    appId: '1:932325401767:ios:76eed2fb3757810385a782',
    messagingSenderId: '932325401767',
    projectId: 'dm-managment',
    storageBucket: 'dm-managment.appspot.com',
    iosBundleId: 'com.devmarkaz.early.staging.anon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6rqJfnhejTI80zYUROAW1_Wve8wvKlmw',
    appId: '1:932325401767:ios:292c06fa510fd81f85a782',
    messagingSenderId: '932325401767',
    projectId: 'dm-managment',
    storageBucket: 'dm-managment.appspot.com',
    iosBundleId: 'com.devmarkaz.devmarkaz.RunnerTests',
  );
}
